branches:
  only:
    - master
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autopoint check
script: ./autogen.sh && ./configure && make -j4 && make check
notifications:
  email:
    recipients:
      - jamesodhunt@ubuntu.com
